# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-16 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicTraits',
            fields=[
                ('fat', models.TextField(blank=True, db_column='FAT', null=True)),
                ('age', models.TextField(blank=True, db_column='AGE', null=True)),
                ('sex', models.TextField(blank=True, db_column='SEX', null=True)),
                ('basic_traits_id', models.TextField(blank=True, db_column='Basic_Traits_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Basic_Traits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BirdInfo',
            fields=[
                ('number', models.TextField(blank=True, db_column='NUMBER', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Bird_Info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('date_collected', models.TextField(blank=True, db_column='DATE_COLLECTED', null=True)),
                ('arrived_amnh', models.TextField(blank=True, db_column='Arrived_AMNH', null=True)),
                ('collector_s_field', models.TextField(blank=True, db_column='COLLECTOR(S)', null=True)),
                ('collection_id', models.TextField(blank=True, db_column='Collection_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Collection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComplexTraits',
            fields=[
                ('weight_g_field', models.DecimalField(blank=True, db_column='WEIGHT_(g)', decimal_places=1, max_digits=3, null=True)),
                ('testes_r', models.TextField(blank=True, db_column='TESTES_R', null=True)),
                ('testes_l', models.TextField(blank=True, db_column='TESTES_L', null=True)),
                ('ovaries', models.TextField(blank=True, db_column='OVARIES', null=True)),
                ('complex_traits_id', models.TextField(blank=True, db_column='Complex_Traits_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Complex_Traits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('prep', models.TextField(blank=True, db_column='PREP', null=True)),
                ('trap', models.TextField(blank=True, db_column='TRAP', null=True)),
                ('depredation_method', models.TextField(blank=True, db_column='DEPREDATION_METHOD', null=True)),
                ('death_id', models.TextField(blank=True, db_column='Death_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Death',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Identifiers',
            fields=[
                ('identification', models.TextField(blank=True, db_column='IDENTIFICATION', null=True)),
                ('country', models.TextField(blank=True, db_column='COUNTRY', null=True)),
                ('identifiers_id', models.TextField(blank=True, db_column='Identifiers_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Identifiers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('state', models.TextField(blank=True, db_column='STATE', null=True)),
                ('county', models.TextField(blank=True, db_column='COUNTY', null=True)),
                ('precise_locality', models.TextField(blank=True, db_column='PRECISE_LOCALITY', null=True)),
                ('latitude', models.TextField(blank=True, db_column='LATITUDE', null=True)),
                ('longitude', models.TextField(blank=True, db_column='LONGITUDE', null=True)),
                ('location_id', models.TextField(blank=True, db_column='Location_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('specimen_prep', models.TextField(blank=True, db_column='SPECIMEN_PREP', null=True)),
                ('preparator', models.TextField(blank=True, db_column='PREPARATOR', null=True)),
                ('preparation_id', models.TextField(blank=True, db_column='Preparation_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Preparation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreSkin',
            fields=[
                ('beak_length_mm_pre_skin_field', models.DecimalField(blank=True, db_column='Beak_length_mm_(Pre-Skin)', decimal_places=2, max_digits=5, null=True)),
                ('beak_depth_mm_pre_skin_field', models.DecimalField(blank=True, db_column='Beak_depth_mm_(Pre-skin)', decimal_places=2, max_digits=5, null=True)),
                ('head_length_mm_pre_skin_field', models.DecimalField(blank=True, db_column='Head_length_mm_(Pre-Skin)', decimal_places=2, max_digits=5, null=True)),
                ('wing_length_mm_pre_skin_field', models.DecimalField(blank=True, db_column='Wing_length_mm_(Pre-Skin)', decimal_places=2, max_digits=5, null=True)),
                ('tail_length_mm_pre_skin_field', models.DecimalField(blank=True, db_column='Tail_length_mm_(Pre-Skin)', decimal_places=2, max_digits=5, null=True)),
                ('tarsus_length_mm_pre_skin_field', models.DecimalField(blank=True, db_column='Tarsus_length_mm_(Pre-Skin)', decimal_places=2, max_digits=5, null=True)),
                ('notes_pre_skin_field', models.TextField(blank=True, db_column='Notes_(Pre-Skin)', null=True)),
                ('pre_skin_id', models.TextField(blank=True, db_column='Pre_Skin_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Pre_Skin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('beak_length_mm_skin_field', models.DecimalField(blank=True, db_column='Beak_length_mm_(Skin)', decimal_places=2, max_digits=5, null=True)),
                ('beak_depth_mm_skin_field', models.DecimalField(blank=True, db_column='Beak_depth_mm_(Skin)', decimal_places=2, max_digits=5, null=True)),
                ('head_length_mm_skin_field', models.DecimalField(blank=True, db_column='Head_length_mm_(Skin)', decimal_places=2, max_digits=5, null=True)),
                ('wing_length_mm_skin_field', models.DecimalField(blank=True, db_column='Wing_length_mm_(Skin)', decimal_places=2, max_digits=5, null=True)),
                ('tail_length_mm_skin_field', models.DecimalField(blank=True, db_column='Tail_length_mm_(Skin)', decimal_places=2, max_digits=5, null=True)),
                ('tarsus_length_mm_skin_field', models.DecimalField(blank=True, db_column='Tarsus_length_mm_(Skin)', decimal_places=2, max_digits=5, null=True)),
                ('notes_skin_field', models.TextField(blank=True, db_column='Notes_(Skin)', null=True)),
                ('skin_id', models.TextField(blank=True, db_column='Skin_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Skin',
                'managed': False,
            },
        ),
    ]
